apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: syedamaseera/my-node-app:855e6abe0245df4b1bc2d2e19862b28cf058320f
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30080
